export default {
    Today: 'YYYY-MM-DD',
    YYYYMMddHHmm: 'YYYY-MM-DD HH:mm',
    Now: 'YYYY-MM-DD HH:mm:ss',
    HHmm: 'HH:mm',
    HHmmss: 'HH:mm:ss',
    Year: 'YYYY',
    Month: 'MM',
    Day: 'DD',
    Hour: 'HH',
    Minute: 'mm',
    Sec: 'ss',
    MMYY: 'MM/YY',
    FileName: 'YYYYMMDD_HHmmss',
};
